# Generated by Django 3.1.7 on 2021-04-07 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='doi',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='seen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reference',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memoire.country'),
        ),
    ]
